version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - rabbitmq
      - redis  # Add Redis as a dependency
    environment:
      - MONGO_URI=mongodb://mongo:27017/test_db
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URI=redis://redis:6379  # Environment variable for Redis connection
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  redis:
    image: redis/redis-stack:latest  # Using the Redis stack image
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
